# This is a sample aws-auth-patch.yml file.
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::034811162232:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-S5C2TG8YM0LP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::034811162232:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-26T00:23:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1790"
  uid: c8e082d8-bde8-4465-a1bc-77ec7b93c3ad